### ISSUE TITLE
Single demo with Kappamap and Shearmap overlay

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#36]
We should combine all map demos into a single demo that explains how to use and plot Kappamaps and Shearmaps, and then overlay one with the other to visually check if the shear and convergence maps align correctly.

**Comment by drphilmarshall** [comment]
This demo looks good to me: I'm tidying it up a little (including fixing the import statement) and will move this demo and the others into their own folders. @sweverett, you'll need to set a `PANGLOSS_DIR` environment variable in your .bashrc file so that `ipython` knows where to look for the `pangloss` module:

```
export PANGLOSS_DIR='/home/spencer/Documents/Pangloss'
```

Nice work!
