### ISSUE TITLE
WLMaps need to be able to plot themselves in world coordinates

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#41]
This means we need a method to parse Stefan's filenames to extract the world coordinates (Ra, Dec) of the map field center. Since all his maps have the same size and pixel scale, we can carry on hard coding these in the `read_binary_data()` method. When we start working with other sims we'll add more io methods anyway.

**Comment by sweverett** [comment]
One big issue has come up by converting everything to world coordinates. Since we decided to set the origin of our system at the center of the (0,0)  map, the right ascension value switches from 0 to 360 in between only one bin. While this is correct, I don't think the 'image2world()' and 'world2image()' methods were designed with this in mind. This is resulting in negative pixel locations when trying to use coords='world' for subplots and breaking the code. We either need to reset our origin to be the bottom left of the (0,0) map or fix 'image2world()/world2image()' so that it can handle this case.

**Comment by drphilmarshall** [comment]
I guess if world2image() ever returns a negative pixel number in the
i-direction (parallel to RA), we should undo the 360 deg offset and try
again. Or is there another problem as well?

**Comment by sweverett** [comment]
You're right, that fixed it. I'll change 'world' to be the default now.
