### ISSUE TITLE
Create BackgroundCatalog class

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#45]
We need to create another subclass of `Catalog` that contains galaxy catalog information for the background galaxy sources that are weakly lensed by the foreground galaxies. Each `BackgroundCatalog` object should be able to generate N galaxies that are uniformly distributed in an inputted domain, along with uniformly distributed ellipticities and intrinsic shapes. Each source should be at a redshift of z=1.3857 as this is where Stefan's ray tracing was done from. `BackgroundCatalog` should be able to plot itself (along with the optional subplots, units, etc from previous plotting methods), both on its own and overlaid over `ForegroundCatalog`'s and `WLMap`'s. We should also determine how to represent the orientation of a source galaxy, perhaps with a colored stick with size proportional to magnitude similar to `ShearMap` objects. `Catalog`'s `generate()` method can either be modified or absorbed into `BackgroundCatalog` to accomplish much of this.

**Comment by tcollett** [comment]
Quick comment: just remember that in real data the background objects will
often be foreground objects as well. i.e. a source at z=1 will be lensed
and also be a lens for a source at higher redshift. Make sure you build
infrastructure that can cope with this.

**Comment by drphilmarshall** [comment]
Good point, thanks Tom. @sweverett can you please have the generate method write each background galaxy redshift to the catalog as a column for this reason? Also, let's check the catalog after reading in, it must have a redshift column (otherwise we can't compute shears correctly).

Interestingly, Stefan's foreground catalogs are also background catalogs, in the sense that his mock galaxies have lensed positions and brightnesses... In the end I'm imagining using the same catalog as both foreground and background. When we request more simulated data, we should ask for just such a catalog, with Ray traced shear and convergence provided for each one. Perhaps @beckermr is already making such things as standard?

**Comment by sweverett** [comment]
A lot of progress has been made with `BackgroundCatalog`, but plotting the final result isn't very convincing. In the subplot below, the yellow circles are the most massive foreground galaxies, the blue ellipses are the background sources with their intrinsic shapes, and the green ellipses are the lensed background sources.
![lensed_galaxies](https://cloud.githubusercontent.com/assets/8742179/8613430/e48cda5e-2693-11e5-82b2-17e9fc127a10.png)
All of the positions are aligned, but the angular alignment of the lensed galaxies looks off.  Some of the background sources near the center of massive objects are barely lensed, while other galaxies near no significant convergence or shear are lensed heavily. Likely this is just an error in the lensing calculation, I'll do more testing tomorrow.

**Comment by drphilmarshall** [comment]
Great plot! Lensing bug should be easy to find - I'll take a look at the code too.
