### ISSUE TITLE
Background catalogs should be able to compare their different correlation functions

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#70]
We need to write a `compare_corr()` method in `BackgroundCatalog` that will compare two correlation function objects returned by `calculate_corr()` using a chi-squared test, and determine the significance of the discrepancy.

**Comment by sweverett** [comment]
I ran the `compare_corr()` method for the observed and predicted galaxy-galaxy correlation of the following plot:

![compare_corr](https://cloud.githubusercontent.com/assets/8742179/9067947/3f45f81c-3a95-11e5-8fbb-c791e81e79c0.png)

It returned a chi^2 value of 46.6 and n_sigma =1.29. I realize our model doesn't fit the observed data very well at large and small scales, but I was surprised by how large chi^2 was. Is the value around what you would expect? Still new to this.

**Comment by drphilmarshall** [comment]
I count 35 "data" points in each correlation function, so chisq = 46.6
being above 35 is good (it's a bad fit). There are 11 points at high \Delta
theta with very significantly different values though, so I woudl have
expected the chisq to come out higher than that (if two points are
separated by 10 times the combined error bar, they contribute 100 to
chisq). Might be worth double checking the chisq is summing correctly.

I think you have nsigma correctly calculated though: 1.29 =  sqrt(2_46.6) -
sqrt(2_35) so that's good!

BTW when you compute the mean percentage difference you'll need to do some
error propagation so you can report numbers like (52+/-1)%
