### ISSUE TITLE
Is our halo mass definition correct? How about our source redshift?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#91]
@sjhilbert replies:

> > Another possibility is that we are using the wrong definition of halo mass. In the catalog readme.txt file, I see:
> > 
> > `M_Halo[M_sol/h]     virial mass of the main halo of galaxy in solar mass /h (sorry, still have to check which overdensity threshold is used)`
> 
> For for "_SA_" and "_Guo_", it is M_200crit (i.e. mass enclosed in sphere with mean density = 200 \* critical density). For "_Bower_" it is not clear.

@sweverett can you please double check that we are interpreting the catalog halo masses correctly?

Stefan, you might like to read Spencer's [SULI report](https://github.com/drphilmarshall/Pangloss/raw/wl/doc/FinalPaper_SEverett.pdf) to see the problem we are worrying about: ellipticity correlation function predicted by our manipulation of the halos in your catalog is under predicted relative to the  ellipticity correlation function of the background galaxies in the same catalog. 

Another double-check: Stefan, what source redshift should we be using, please?

**Comment by sweverett** [comment]
I checked `example.config` and we are currently using the subhalo mass `M_subhalo` in Stefan's foreground catalogs for the individual galaxy halo masses, which is good news. I'll continue to look into the halo mass definition, but the absence of the main halo masses may be a part of our missing shear power in the ellipticity-ellipticity correlation function.

**Comment by drphilmarshall** [comment]
Right! Select a halo, find all its sub-halos, and see if any of them have
subhalo mass = halo mass. If none of them do, then we'll need to add in the
halo as well as all the sub-halos, at the position of the central galaxy.
(Which galaxy is the central one would be TBD.) Any that do have subhalo
mass = halo mass will be the centrals (by definition), and if that's the
case then our lack of shear correlation power must have some other
explanation.

**Comment by sweverett** [comment]
Hmm, some interesting results. For the foreground catalog (0,0,0,0) in `Pangloss/data`, there are 3256 galaxies with subhalo masses equal to the halo mass (~1.1%). However, there are 25,973 galaxies that have normal halo mass but 0 subhalo mass (~9%). I"ll read more of Stefan's paper, but right now it's not clear to me whether the central galaxies are those with subhalo mass = halo mass (what I was expecting) or galaxies that have _only_ halo mass. If it is the latter, then we are not accounting for a large percentage of the mass.

**Comment by drphilmarshall** [comment]
Whoah. Now we have two puzzles! What does halo mass = subhalo mass mean,
and what does zero subhalo mass mean? cc @sjhilbert

**Comment by sjhilbert** [comment]
from readme.txt:

List of currently stored properties:

GalID               unique ID of source galaxy of galaxy image
HaloID              unique ID of main halo (can be galaxy, group, or cluster halo) the source galaxy is located in
SubhaloID           unique ID of subhalo the galaxy is centre of (if there is a subhalo)
Type                0 = central galaxy of the main halo, 1 = non-central galaxy of the main halo, but with subhalo, 2 = non-central galaxy without subhalo (at least for the MPA Garching galaxy model)
PlaneNumber         ID of lens plane in ray-tracing the galaxy is associated with
z_spec              "spectroscopic" redshift of the galaxy (includes cosmological redshift and peculiar motion Doppler shift)
pos_0[rad]          first sky position coordinate in radian (can be positive and negative)
pos_1[rad]          second sky position coordinate in radian (can be positive and negative)
Dc_los[Mpc/h]       comoving line-of-sight distance to source galaxy in Mpc/h
M_Halo[M_sol/h]     virial mass of the main halo of galaxy in solar mass /h (M_200crit for "_SA_" and "_Guo_", sorry, still have to check which overdensity threshold is used for "_Bower_")
M_Subhalo[M_sol/h]  gravitationally bound mass of the subhalo of galaxy in solar mass/h (note that the Bower model does not really know subhalos)
M_Stellar[M_sol/h]  stellar mass of galaxy
mag_SDSS_u          SDSS u-band apparent observer-frame AB magnitude (also contains magnification effects)
mag_SDSS_g          SDSS g-band apparent observer-frame AB magnitude (also contains magnification effects)
mag_SDSS_r          SDSS r-band apparent observer-frame AB magnitude (also contains magnification effects)
mag_SDSS_i          SDSS i-band apparent observer-frame AB magnitude (also contains magnification effects)
mag_SDSS_z          SDSS z-band apparent observer-frame AB magnitude (also contains magnification effects)
mag_J               2MASS J-band apparent observer-frame magnitude (also contains magnification effects)
mag_H               2MASS H-band apparent observer-frame magnitude (also contains magnification effects)
mag_K               2MASS K-band apparent observer-frame magnitude (also contains magnification effects)

A galaxy is central if Type is 0, and not a central if Type > 0. The virial mass (M_200crit) of the central halo is stored in M_halo. This should be non-zero for all galaxies, since all galaxies live in halos. However, not all galaxies live in subhalos. If Type is 2, then the galaxy does not have  a subhalo, and M_Subhalo is zero. Moreover, M_Subhalo < M_halo for many central galaxies (in particular for those that have satellites).

For a simple halo model, one can assign to all central galaxies a halo with mass M_halo and no halo to non-central galaxies (giving them a halo would be double counting). Alternatively, one can assign to all galaxies a (sub)halo with mass M_Subhalo. Note that in any case, at most 50 % of all mass is bound in halos. Half the mass in the Universe (or more) is not accounted for by such a halo model.

**Comment by sweverett** [comment]
Thanks @sjhilbert ! That clears up quite a bit, and encourages the need for #65.

**Comment by drphilmarshall** [comment]
From Stefan's explanation it seems like central galaxies (Type 0) should be given both a halo _and_ subhalo, with listed masses, and that Type 2 galaxies should be ignored. This is all just while checking this 50% claim, though: when we move to inference just based on the magnitudes (or "equivalently," observed photoz's and stellar masses), we'll need to (slightly wrongly) just assign a halo/subhalo to every galaxy without knowing (yet) its type. Can you try this, please Spencer? Thanks!

**Comment by sjhilbert** [comment]
> From Stefan's explanation it seems like central galaxies (Type 0) should be given both a halo and subhalo

no.
pick whether you want to use halos only or subhalos only.

**Comment by drphilmarshall** [comment]
Oh! Sorry - my mistake. Sounds like just using the subhalo masses is the
way to go.

Quick question: do the subhalo masses of all the galaxies in a group add up
to that group's halo mass?

**Comment by rhw** [comment]
No, definitely not.  Most of the mass is in the host.

**Comment by sjhilbert** [comment]
I suspect, the subhalo masses (including the "main subhalo" of the central galaxy) + unbound mass (according to subfind) should add up to the FoF mass, which is similar to the halo mass M_200crit. I am not sure what the fraction of unbound mass in the FoF  groups is (but I guess it's not very large), and how close M_FoF and M_200crit are. So it may be good to compare the sum of subhalo masses and the halo mass.

**Comment by drphilmarshall** [comment]
@sjhilbert OK, that makes sense: we should indeed check the sums of subhalo masses. Just browsing the catalog, for example, I find this funny little group:

```
GalID HaloID SubhaloID Type M_Halo[M_sol/h] M_Subhalo[M_sol/h] M_Stellar[M_sol/h]
23003339000771 23003339001608 32002300000469 2 1.15535e+13 0 8.06126e+09
23003339001406 23003339001608 32002300000469 2 1.15535e+13 0 6.01061e+09
23003339001615 23003339001608 32002300000469 2 1.15535e+13 0 2.00791e+10
23003339001583 23003339001608 32002300000469 2 1.15535e+13 0 2.4211e+10
23003339001659 23003339001608 32002300000469 2 1.15535e+13 0 1.27349e+10
23003339001242 23003339001608 32002300000469 0 1.15535e+13 1.01514e+13 5.45561e+10
23003339005111 23003339001608 32002300000469 2 1.15535e+13 0 3.05302e+09
```

Seven galaxies with unique IDs and stellar masses. One is type 0 and lives in a "subhalo"  of mass 1.01514e+13. Its "halo" is listed as having slightly higher mass, 1.15535e+13 - so I guess `subfind` found almost all the mass that the halofinder had previously assigned to this group, but not quite all of it? I see that none of the other group members have been found to have their own subhalos, so they are listed as type 2, and have zero "subhalo mass". I don't understand how the galaxy positions were generated in this case, if not by being placed at the center of non-massless subhalos, but perhaps mine is not to reason why! :-)

Anyway, to remind ourselves: at the moment we are still just trying to compute the lensing effect due to the objects in the mock galaxy catalog, assuming that we magically have knowledge of the halos and subhalos as well. But, note that the simplest possible inference we could make (in the near future) would be to assume a single stellar mass to halo mass relation and apply it to every galaxy we see, and infer the resulting "halo masses" (and the hyper-parameters that govern the relation). Even if we could do this, we would infer galaxy dark matter "halo masses" that were systematically different from the  "true subhalo masses" in the catalog, many of which are zero! I'm not sure this is necessarily a problem, its just something to bear in mind: comparing "true" and "observed" galaxy dark masses on an individual object basis may not be a comparison that makes much sense.

**Comment by sjhilbert** [comment]
> I don't understand how the galaxy positions were generated in this case

It is based on tracking the particle, that was the most bound when there was still a subhalo. But that particle's orbit does not decay enough any more after the subhalo is dissolved (not enough friction any more), so the more recent Garching models put the type-2 galaxies somewhere between the halo center and the once-most-bound particle position, so that the satellite galaxy will end up in the halo center after some merging time (and the stars of the satellite galaxies are transferred to the central galaxy).

> Even if we could do this, we would infer galaxy dark matter "halo masses" that were systematically different from the "true subhalo masses" in the catalog, many of which are zero! I'm not sure this is necessarily a problem, its just something to bear in mind: comparing "true" and "observed" galaxy dark masses on an individual object basis may not be a comparison that makes much sense.

That is definitely a problem inherent to the approach. Question is: is it useful to look at the resulting uncertainties on the level of halo masses, or should we just focus on the effects on the lensing?

**Comment by drphilmarshall** [comment]
Probably the latter, I think: we must fit the lensing data! But all this is
a good reminder that as we develop our model, we must keep in mind that the
representation of the simulation output as a catalog of halos, subhalos and
galaxies is itself an approximation...
