### ISSUE TITLE
Early comments on draft thesis

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#98]
Looks like you are on track. Below are some comments and questions you might expect to get from an examiner like me!
- The lensing convergence maps should only show over- and under-density relative to the cosmological mean. Did you subtract off the mean density before computing the maps in Fig 13? This might explain the gray background. Can you explain why _not_ subtracting the mean density in this way is equivalent to including all the mass in the universe twice?
- How does a threshold in halo relevance translate into numbers of halos retained? I think I'd prefer to see Figure 5 illustrate this, rather than the mean or max relevance per lightcone (which is not a quantity we would ever need). What threshold / halo number (or retention fraction) was used in each figure?
- Can you explain the scaling with N in both the ABC and likelihood analyses methods, from the functional forms of the log likelihood and the correlation functions?
- It may not be possible to draw too strong a conclusion about ABC yet. Under what circumstances would it be competitive? In the end we only care about _total_ run time.
- In Figure 10 and 11 you illustrate the accuracy of the halo model in one light cone, with the gaps between the correlation functions from the ray tracing and the halo model being of great interest. How do these differences (on their various scales) relate to what we can see in the residual convergence map? (You have a placeholder for this discussion in 6.1 I see)
- In section 4.5, how does the CPU time spent in different parts of the log likelihood calculation break down? What do we need to do faster?
- The $\xi_{-}$ component is not expected to be exactly zero, just lower amplitude than $\xi_{+}$ (your red/blue plots show why). I believe the $\xi_{x}$ component due to lensing is expected to be zero (in the single plane lensing approximation, and still very small otherwise), so this is why we focus on it.
- You need a title, a better abstract, and bulleted lists of both questions to answer (in the intro) and conclusions to match (in the final section), all ASAP! :-)

**Comment by sweverett** [comment]
Thanks for taking a look and making comments!
- I did not subtract off the mean density before computing the maps in Figure 13. Using the definition of convergence that I see in the literature (projected surface mass density / critical mass density) I don't see how what I'm doing would be accounting for extra mass, but if Stefan's maps have kappa=0 correspond to mean density then clearly I am. I guess this must be the case since his maps often have negative convergence values. But then this is a problem with our kappa predictions and not just the maps, isn't it?
- I agree that this is a much more useful result. I also plan on plotting the NRMSE of the shear-shear correlation function as a function of # of relevant halos in this section.
- Yep! I was planning on this but hadn't had time yet to take the data.
- I agree that total run time is all that matters in the end, but both the likelihood calculation and correlation function calculation require the same steps beforehand. I can only see ABC being competitive if it scales with N much more slowly than the likelihood calculation.
- Figures 10 and 11 are correlation functions from the lensed ellipticities of all background sources, not from one lightcone. As you pointed out, I was going to leave that discussion for section 6.1.
- Did you mean CPU time breakdown for the lensing calculation? That is coming as well, but I wanted to optimize the smooth-component correction first as the first implementation is significantly slowing down the prediction time.
- That makes sense – thanks!
- Agreed!

I'll try to get most of this done as quickly as I can so you can scan it over before I make finishing touches and turn the thesis in!

**Comment by drphilmarshall** [comment]
The problem is that the cosmological distances we use assume a homogeneous universe with mean density equal to Omega_m rho_crit. If we fill up our mass model so that it has mean density equal to Omega_m rho_crit, then when we predict lensing effects we'll have precisely 2 times as much mass in the model as we should have. I think we need to subtract off the global mean density Omega_m rho_crit in each redshift slice before computing the convergence contribution of that plane. That should give us a final kappa map whose mean is close to zero.

Another way to look at ABC's competitiveness is as follows: if the CPU time is totally dominated by predicting the shears, then it doesn't matter whether we spend epsilon1 calculating the likelihood or epsilon2 computing correlation function summaries and ABC distances - _unless_ we need to generate many more (or fewer!) ABC samples than posterior samples. We don't yet know which is going to be the more efficient sampling method, ABC or importance sampling or MCMC, or whatever, but it's _not unreasonable_ to suppose that all these methods will be _comparably efficient_. It's a question for further work though. If the CPU time is dominated by shear prediction, this a) makes the choice of sampling method less important, and b) suggests we need to invest in more efficient computation of shear, via parallelization or using databases or something. If the shear prediction time is dominated by IO in some way, that would suggest databases could be important. If its special functions, then parallelization is the thing to look at. 

Good luck! Let me know when you're ready for final feedback!
